# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'GoogleSignIn', '~> 4.1'
  # Pods for RNLogin

  target 'RNLogin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
